### ISSUE TITLE
Save data to a Playbook 

### ISSUE THREAD

**Issue by GouravSardana** [IndianOpenSourceFoundation/dynamic-cli#85]
As you all know our Dynamic CLI is used to find out answers from Stackoverflow. What if users want to save that question to their playbook.

Idea is to maintain a playbook in their local storage where all the package data will store and we can add an option after giving the answers to the StackOverflow question - Do you want to save this in your playbook? Y/N

If users replied yes then save it to their local storage and if users want to get those data back use - dynamic --playbook or dynamic --p. It will display the data in table form.

**Comment by pranavbaburaj** [comment]
Maybe, we can create a `json` file and add it to the environment variable, from which the file is later accessed.  We can output tables to the console using [`prettytabe`](https://github.com/jazzband/prettytable)

**Comment by GouravSardana** [comment]
Nops. That works but we need to use some effective way to store the data. Later on, we can sync that data with the Notion/Github of the user. So that they can also access and it will save in the cloud for future purpose.

**Comment by GouravSardana** [comment]
@pranavbaburaj BTW can you explain your approach to save the data into playbook?

**Comment by NamamiShanker** [comment]
I think it will be easy to do this. JSON or CSV any would work and saved answers can be stored in user config folder for Dynamic CLI. The data can be stored with fields like - time, ques_id, ques_link, ques_title, ans_id, ans_link, ans_title. 

Later the playbook feature can access the file, present the questions which can be cycled over with arrow keys and its saved answer will be displayed below the question list. We would need to add a feature to remove entries from the playbook also. And some way to efficiently sync the cloud and local counter part of playbook. Question IDs can be used as primary key for that since we are only saving the most upvoted result of question.

**Comment by GouravSardana** [comment]
Sounds good. We can go ahead with json because later on we can use that to sync it with Notion/Github repo.

**Comment by NamamiShanker** [comment]
I would like to work on this issue

**Comment by NamamiShanker** [comment]
Great! Please assign me to it.

**Comment by NamamiShanker** [comment]
I am saving JSON data in a `playbook.json` file in the following format:
```
[
            {
                question_id: 123456,
                question_title: 'question_title',
                question_link:  'link',
                answer_body: 'body of the answer'
            },
            ...
 ]
```
Is this alright? Or should I change the format?

**Comment by GouravSardana** [comment]
For now, format is alright but it should be in append mode. Let's say i save a question once there were 2 possibility - 
1. Question already exist.
2. If not exist then it will append the file rather than creating a new one.
